version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379" 
    networks:
      - my-network

  cab432-backend:
    build: ./
    ports:
      - "3001:3001" 
    networks:
      - my-network
    depends_on:
      - redis

  

networks:
  my-network:
    driver: bridge